### ISSUE TITLE
NuGet package not packaged properly?

### ISSUE THREAD

**Issue by Andy-Corrigan** [Sicos1977/QPdfNet#1]
Hi,

I've imported your package and dependencies from NuGet - the intellisense and stuff works perfectly. However, when I attempt to run a quick test, I'm met with this exception: 

[DllNotFoundException: Failed to find library 'qpdf29.dll' for platform x64]

I'm guessing it's as simple as you doing some sort of versioning in the name of the DLL, as opposed to the metadata of it? 

For now I can probably work around it by renaming the DLL manually, but it's probably something worth looking at.

**Comment by Andy-Corrigan** [comment]
Scrap that, renaming the DLL doesn't work - that results in: 

System.IO.FileLoadException: Could not load file or assembly 'QPdfNet29' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by Sicos1977** [comment]
Weird, I use the same nuget package in my own project and have no problems at all. Can you check if there is a X64 and X86 folder in your solution with in those folders the library qpdf29.dll?

**Comment by Andy-Corrigan** [comment]
I had the folders, but not that DLL - went to the web interface and downloaded the package that way, unzipped it and plonked them in the file structure manually and it worked.

**Comment by Sicos1977** [comment]
Good to hear that you got it solved
