### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by deralbert** [Sicos1977/QPdfNet#12]
I recommend cleaning up the repository. I analyzed your `.gitignore` file, and many items are already excluded. However, I suspect that before the file was added, many directories were committed that are now excluded. This significantly impeded the readability of the commits because numerous generated files were consistently being included in each commit.

My suggestion:

0. Remove the line "x64" from the `.gitignore` file, since the files under QpdfNetTest\x64 are needed for the tests.
1. Open "Git Bash Here" in the directory with the local repository and .git.
2. Execute `git ls-files -i --exclude-standard --directory -z| xargs -0 rm -r -f &> /dev/null`
3. Make a commit and push.

This will delete all files ignored by `.gitignore`.

**Comment by deralbert** [comment]
Could you please generate a new NuGet package afterward? I would be delighted to integrate your library into the main project.

**Comment by Sicos1977** [comment]
ALready did it... just wondering because of your name on GitHub ... are you from Germany?

**Comment by deralbert** [comment]
Ja. :blush:

**Comment by Sicos1977** [comment]
Ah okey ... Nederland hier.

**Comment by Sicos1977** [comment]
Thanks for your work and I'll close this issue

**Comment by deralbert** [comment]
Thank you for your support and quick response to my issues.

**Comment by Sicos1977** [comment]
You did most of the hard work so I wont complain :-)
