### ISSUE TITLE
System.AccessViolationException occurs when calling Run() in an application targeting the x86 architecture

### ISSUE THREAD

**Issue by deralbert** [Sicos1977/QPdfNet#15]
**Brief description**
When utilizing QPdfNet and targeting the `x86` architecture, an exception occurs: `System.AccessViolationException - 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'` The issue arises within the `InternalRun` method in `Job.cs`.

**Repro steps (superficially)**
1. Add QPdfNet as a NuGet package to your program.
2. Choose the `x86` architecture for your program.
3. Include test files, create a job, and execute something like `var result = job.InputFile(pdfPath).Check().Run(out var output)`. This immediately triggers the `System.AccessViolationException`.

Yes, unfortunately, I am still compelled to release both an `x86` and an `x64` version of the application.

**Cause**
`private delegate int CallbackDelegate(IntPtr data, int length, IntPtr udata)` in `Job.cs`.

According to the [platform default calling convention](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/calling-conventions#platform-default-calling-convention):
> For the x86 architecture, the default calling convention is platform specific. Stdcall ("standard call") is the default calling convention on Windows x86 and it is used by most Win32 APIs. Cdecl is the default calling convention on Linux x86. Windows ports of open-source libraries that originated on Unix often use the Cdecl calling convention even on Windows x86. It's necessary to explicitly specify the Cdecl calling convention in P/Invoke declarations for interop with these libraries.
> 
> For non-x86 architectures, both Stdcall and Cdecl calling conventions are treated as the canonical platform default calling convention.

**Proposed fix**
In the case with the qpdf library, the `Cdecl` calling convention is used, irrespective of the architecture. The mentioned delegate must be annotated in advance with the [`UnmanagedFunctionPointerAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedfunctionpointerattribute), specifying the `Cdecl` calling convention:
```cs
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
private delegate int CallbackDelegate(IntPtr data, int length, IntPtr udata);
```

**Comment by deralbert** [comment]
I would be grateful if you could publish the new version 1.4.2 of the package. Could you please also update the **Release** section on the main project page in GitHub? According to this page, the latest version is still 1.4.0.

**Comment by Sicos1977** [comment]
I just released a new nuget package.
