### ISSUE TITLE
Issue with Non-ASCII Characters in File Paths

### ISSUE THREAD

**Issue by maciej-podgorski** [Sicos1977/QPdfNet#18]
The library seems to have an issue handling file paths that include non-ASCII characters, such as 'ą' or 'ć'. 
The following code:
```
using QPdfNet;

string? output;

new Job().InputFile(@"D:\abc\test.pdf").Check().Run(out output);
Console.WriteLine(output);

Console.WriteLine();

new Job().InputFile(@"D:\ąbć\test.pdf").Check().Run(out output);
Console.WriteLine(output);
```
gives following output:
```
checking D:\abc\test.pdf
PDF Version: 1.4
File is not encrypted
File is not linearized
No syntax or stream encoding errors found; the file may still contain
errors that qpdf cannot detect

qpdfjob json: open D:\?b?\test.pdf: No such file or directory
```
QPdfNet version: 1.4.3
OS: Windows 10
.NET version: 8

**Comment by Sicos1977** [comment]
I tried to marshal the json file that is sent to QPDF as a UnmanagedType.LPWStr string but that gives the same error so I think the problem is in QPDF itself. So it is better to raise an issue there and point it to this one --> https://github.com/qpdf/qpdf/issues

![image](https://github.com/Sicos1977/QPdfNet/assets/6692947/b48a71d0-512b-4973-b24f-79756d404144)

**Comment by Sicos1977** [comment]
No response.... closed

**Comment by schulm** [comment]
@Sicos1977 I had the same problem with the qpdf dll invocation but in another language (Delphi) and non ascii filenames, got it solved with the correct invocation of the dll, maybe setting the Charset to Unicode [1] in [0] (link to doc [3]) will solve the issue.

[0] https://github.com/Sicos1977/QPdfNet/blob/main/QPdfNet/Interop/QPdfApi.cs#L114
[1] https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportattribute.charset?view=net-9.0
[2] https://qpdf.readthedocs.io/en/stable/library.html#a-note-about-unicode-file-names
