### ISSUE TITLE
[Linux][Docker] libqpdf29.dll.so not found

### ISSUE THREAD

**Issue by madik7** [Sicos1977/QPdfNet#2]
Hi,

I've imported your package from NuGet - this lib works perfectly on windows. However, when I attempt to run my application in Docker container, there is exception:

[DllNotFoundException: Failed to find library 'libqpdf29.dll.so' for platform x64]

Do you have any advice, how use this library on Linux/Docker platform ?

**Comment by Sicos1977** [comment]
You tried renaming the file libqpdf29.dll to libqpdf29.dll.so ?

**Comment by madik7** [comment]
Yes, I tried to rename qpdf29.dll to libqpdf29.dll.so but i still see DLLNotFoundException. 
Today I downloaded lib for linux version directly from github release: https://github.com/qpdf/qpdf/releases but i got another error:
`libqpdf29.dll.so: undefined symbol: qpdfjob_run_from_json_with_result `
Are there any differences between the official version of the qpdf library and the one used in QPdfNet?

**Comment by madik7** [comment]
Ok, I found: https://github.com/Sicos1977/qpdf/ and build lib from sources on linux platform. I will check later if it helped

**Comment by madik7** [comment]
I build from your qpdf source, copy output .so file and now it works perfect in Docker container!
