### ISSUE TITLE
Exception System.Reflection.TargetInvocationException on example Encrypt code

### ISSUE THREAD

**Issue by ryangriggs** [Sicos1977/QPdfNet#3]
When attempting to run the Encrypt example code, the application throws this exception:
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
Inner Exception
ArgumentNullException: Value cannot be null.
Parameter name: ptr
This exception was originally thrown at this call stack:
    [External Code]

![image](https://user-images.githubusercontent.com/5854489/204851482-c90d6ffb-71e2-41ed-9bf5-14eb7e4017bf.png)

![image](https://user-images.githubusercontent.com/5854489/204851502-9b749f1a-e2c7-436a-ae85-ae438180296f.png)

I downloaded the latest QPDF MSVC 32-bit and 64-bit builds from the QPDF project and copied all the files in the 'bin' folder of each one into the project's /bin/debug/x86 and /bin/debug/x64 folders, respectively.

**Comment by Sicos1977** [comment]
_I downloaded the latest QPDF MSVC 32-bit and 64-bit builds from the QPDF project and copied all the files in the 'bin' folder of each one into the project's /bin/debug/x86 and /bin/debug/x64 folders, respectively._

That is the reason that it does not work, I added an interface that is needed to communicatie with QPDF from C# and that is now missing.

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/QPdfNet/blob/main/QPdfNet/Interop/QPdfApi.cs

**Comment by ryangriggs** [comment]
Your answer doesn't explain how to fix the problem... Is the issue on my end or on the QPdfNet side? Did QPDF change the DLL so now your interface doesn't work? Or do I need to import the QPdfApi.cs file into my project? or is there some other way to solve this?
 You added an interface and it's missing? Why is it missing if you added it?  Where is it missing from? the QPDFNet project or the QPDF project, or **my** project?
Sorry for the confusion but the explanation is not helping me find a solution.

**Comment by ryangriggs** [comment]
To clarify, if I try to run the demo code without downloading the QPDF dll file, I get this exception:
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
Inner Exception
DllNotFoundException: Failed to find library 'qpdf29.dll' for platform x86

**Comment by drepamig** [comment]
> Your answer doesn't explain how to fix the problem... Is the issue on my end or on the QPdfNet side? Did QPDF change the DLL so now your interface doesn't work? Or do I need to import the QPdfApi.cs file into my project? or is there some other way to solve this? You added an interface and it's missing? Why is it missing if you added it? Where is it missing from? the QPDFNet project or the QPDF project, or **my** project? Sorry for the confusion but the explanation is not helping me find a solution.

I had this same issue. It looks like adding the contents of the two subfolders that are added to the project when referencing the nuget package as a resource fixed it.

Either select all the files
![image](https://github.com/Sicos1977/QPdfNet/assets/21010192/975878d9-d3a4-41d0-b89d-9bdb9aec1d96)
and change them to resources:
![image](https://github.com/Sicos1977/QPdfNet/assets/21010192/6a4b83b7-8ead-4fd2-9924-08ccb60e25dd)

**or**

Open the `.csproj` file and add (or update) this below. I'm sure there's a more robust way to achieve this, but I haven't investigated any further.
``` xml
   <ItemGroup>
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\concrt140.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_1.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_2.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_atomic_wait.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_codecvt_ids.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\vcruntime140.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\concrt140.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_1.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_2.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_atomic_wait.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_codecvt_ids.dll" />
    <Resource Include="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\vcruntime140.dll" />
    <Resource Include="x64\qpdf29.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="x86\qpdf29.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_1.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_2.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_atomic_wait.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\msvcp140_codecvt_ids.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\vcruntime140.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_1.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_2.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_atomic_wait.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\msvcp140_codecvt_ids.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\concrt140.dll" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x86\vcruntime140.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\[username]\.nuget\packages\qpdfnet\1.2.1\build\\..\x64\vcruntime140.dll" />
  </ItemGroup>
```
