### ISSUE TITLE
qpdf JSON v2

### ISSUE THREAD

**Issue by billm23** [Sicos1977/QPdfNet#4]
I really like your library, thanks for all the work you put into it. I have a quick question. Will you be updating your library to utilize the new JSON version 2 and functionality introduce with qpdf v11?

**Comment by Sicos1977** [comment]
Yes I'm planning to do that. Just have to make some time for it in the next comming weeks

**Comment by Sicos1977** [comment]
I just released a new nuget version that has the latest qpdf changes in it.

**Comment by billm23** [comment]
This is great! Thank you for your work!

**Comment by Sicos1977** [comment]
I think I added all the new methods that were in the latest version. If you miss something then just let me know. to be honnest there were not so many new methods just a few. The biggest change is that you now can manipulate PDF files with a json file.
