### ISSUE TITLE
tesseract51.dll

### ISSUE THREAD

**Issue by lecramr** [Sicos1977/QPdfNet#5]
Hello,

unfortunately, trying to add your library does not work for me. The correct qpdf29.dll's are copied but named wrong. Therefore the library does not find the DLL when starting. Attached is a screenshot from my IDE as well as from the current Nuget package.

![image](https://user-images.githubusercontent.com/20584823/236298254-3be4322b-bb20-4c3d-a361-ded870db46ee.png)
![image](https://user-images.githubusercontent.com/20584823/236298299-738c379b-e302-48cd-bce4-1df126a10949.png)
![image](https://user-images.githubusercontent.com/20584823/236298443-7d5e6f48-d476-4809-85f2-cce5a10a837a.png)

**Comment by Sicos1977** [comment]
Sorry I will make a new package, for some reason I mixed up a build template... the one from my Tesseract package somehow got into this package.

**Comment by Sicos1977** [comment]
This issue should be fixed now.
