### ISSUE TITLE
System.Runtime.InteropServices.SEHException when calling RunFromJSON

### ISSUE THREAD

**Issue by deralbert** [Sicos1977/QPdfNet#8]
**Context**
I want to use QPdfNet in my .NET Framework 4.8 project. Within the project, I'm modifying PDF documents using [PdfSharp](https://github.com/empira/PDFsharp), but PdfSharp is not very tolerant of errors in the PDF structure. Therefore, I need to validate the documents before making modifications. I plan to do this using QPDF, specifically with the beautiful wrapper QPdfNet. My application runs on a Windows 10 machine.

**Problem**
When calling an external native C++ function, I encounter an exception: `System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'`.

The value of the `ErrorCode `and `HResult `properties of this exception both are `-2147467259`. The stack trace is:
   ```
at QPdfNet.Job.InternalRun(String& output, Byte[]& data) in C:\Temp\QPdfNet\QPdfNet\Job.cs:line 2265
   at QPdfNet.Job.Run(String& output) in C:\Temp\QPdfNet\QPdfNet\Job.cs:line 2298
   at PdfSharpTest.Program.IstPdfDokumentValide(String pdfPath) in C:\Temp\PdfSharpTest\PdfSharpTest\Program.cs:line 67
   at PdfSharpTest.Program.SindPdfDokumenteValide(List`1 pdfPaths) in C:\Temp\PdfSharpTest\PdfSharpTest\Program.cs:line 55
   at PdfSharpTest.Program.Main() in C:\Temp\PdfSharpTest\PdfSharpTest\Program.cs:line 41
```

**Repro steps**
1. Create a new ConsoleApplication project, choose .NET 4.8 or .NET 4.6.2 (I have this exception with both frameworks) as the target framework.
2. In the Main method, add the lines:
```
QPdfNet.Loggers.Console logger = new QPdfNet.Loggers.Console();
var job = new Job(logger);
string pdfPath = "Path/To/A/Pdf/Document.pdf";
var result = job.InputFile(pdfPath).Check().Run(out var output);
```
3. Compile and run the program.

**Observations**
1. The exception does not occur when using the latest version of the framework, net8.0. Even though net8.0 is not officially supported, QPdfNet works seamlessly with it.
2. When I include the function with the built-in `DllImport` attribute in my program, I can call it without any exceptions:
```
[DllImport("qpdf29.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "qpdfjob_run_from_json")]
static extern int RunFromJSON(string json);
```
I suspect the issue lies in how the native function is loaded using `[RuntimeDllImport(Constants.QPdfDllName, CallingConvention = CallingConvention.Cdecl, EntryPoint = "qpdfjob_run_from_json")]`.
3. The built-in Console Logger in QPdfNet reports that all native functions have been successfully loaded, specifically: `Successfully loaded native function 'qpdfjob_run_from_json' with handle '140734778344928'.`

**Comment by deralbert** [comment]
I also developed a C++ program, compiled it as a library (`ConsoleApplicationQpdf.dll`) for the platform x64, copied this library into the x64 directory of my C# program. Subsequently, I added the following lines to the file  `QPdfApi.cs`:
```
[RuntimeDllImport("ConsoleApplicationQpdf.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "wrap"]
int wrap();
```
Next, I incorporated the line `this._native.wrap();` in the constructor `public Job(ILogger? logger = null)` within`Job.cs`. Upon initiating the application, an exception was raised:
`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

I also observed that when importing my function named wrap, the QPDfNet logger output indicated:
```
2024-02-08T12:01:18.663 - Trying to load native function 'wrapEmpty' from the library with handle '140705332002816'
2024-02-08T12:01:18.663 - Successfully loaded native function 'wrapEmpty' with handle '140705332072653'
```
It is noteworthy that the exception persists regardless of whether I invoke the `wrap` function or any other function from the QPDFNet. In all cases, the `System.AccessViolationException` occurs. My intention was to investigate the details of the exception from the original native code.

Here is my C++ program:
```
#include "windows.h"
#include <exception>
#include <iostream>

using namespace std;

extern "C" {
	__declspec(dllexport) int qpdfjob_run_from_json(char const* json);

typedef int (*ImportedFunction)(char const* json);

__declspec(dllexport) const char* wrap()
{
	HMODULE m = LoadLibrary(L"C:\\Temp\\PdfSharpTest\\PdfSharpTest\\bin\\Debug\\net48\\x64\\qpdf29.dll");
	ImportedFunction importedFunction = (ImportedFunction) GetProcAddress(m, "qpdfjob_run_from_json");
	char const* json = "{\r\n  \"inputFile\": \"C:\\\\Users\\\\myname\\\\Desktop\\\\Document.pdf\",\r\n  \"check\": \"\"\r\n}";
	try
	{
		int ret = importedFunction(json);
	}
	catch (const exception& ex)
	{
		return ex.what();
	}

	return 0;
}

};

int main() {
	wrap();
}
```

**Comment by Sicos1977** [comment]
I really have no idea why you get the exception with a .net 4.8 project. I also use it in a 4.8 project and don't have any problems. Are you sure that you are using the correct dll .. e.g. the 32 bit version in a 32bit process and x64 in a 64 bits proces?

**Comment by Sicos1977** [comment]
I tried to console app and also get an exception... I'll try to look into it a little bit more this evening

**Comment by deralbert** [comment]
>Are you sure that you are using the correct dll

No. But I'm not doing anything specific. I don't manually provide the path to the DLL. It should work "out of the box". At least it works so I the target framework is 8.0 (or perhaps 6.0 and above).

One more observation: Your test project has `<TargetFramework>net6.0</TargetFramework>`, and as a result, all tests pass without any exceptions. If you were to choose `net48 `as the target, you might encounter the same exception in the test project.

**Comment by Sicos1977** [comment]
> > Are you sure that you are using the correct dll
> 
> No. But I'm not doing anything specific. I don't manually provide the path to the DLL. It should work "out of the box". At least it works so I the target framework is 8.0 (or perhaps 6.0 and above).
> 
> One more observation: Your test project has `<TargetFramework>net6.0</TargetFramework>`, and as a result, all tests pass without any exceptions. If you were to choose `net48 `as the target, you might encounter the same exception in the test project.

It looks like some kind of interop error... but without an exception that can give me a clue what is going wrong it will probably be hard to figure out why this happens. Even because it works with newer dotnet versions

**Comment by Sicos1977** [comment]
Turning that off fixes the problem for me... don't know if that is still the default option in newer .net projects

![image](https://github.com/Sicos1977/QPdfNet/assets/6692947/b417b2ce-d704-4d5c-84e9-80542303b4e0)

**Comment by deralbert** [comment]
Where do you have this option? The window looks so on my machine (VS 2022 Preview):
<img src="https://github.com/Sicos1977/QPdfNet/assets/909718/97bdaf5d-9585-4faf-a9e8-eb66f5321a3a" width="512">

**Comment by Sicos1977** [comment]
It are the properties from a .net 4.8 console app ... I have Visual Studio 2022 enterprise

**Comment by deralbert** [comment]
I found the circumstances, under wich the exceptions happens. This behavior is probably bot related to QPdfNet. Consider these points:

1. net48 project
2. Comment out the lines
```
SetInfo(_loggerHandle, qpdf_log_dest_e.qpdf_log_dest_custom, infoPointer);
SetWarn(_loggerHandle, qpdf_log_dest_e.qpdf_log_dest_custom, warnPointer);
SetError(_loggerHandle, qpdf_log_dest_e.qpdf_log_dest_custom, errorPointer);
```
in QPdfNet.

After that, no exception is raised.

But in this case, you don't have exit codes. As soon as these lines are in the code, an exception is raised. Have you any idea why it can happens? Key words would be "native function, returns something, StringBuilder in C#".

**Comment by deralbert** [comment]
Yes, this is the cause. At first I tested it in my main program - it is an almost 25 years old big project that targeting net48. Then I tested it in a console app, also targeting .net48. In the `Job` class, the mentioned lines for exit codes commented out.

**Comment by deralbert** [comment]
I successfully obtained the exception text from the C++ library by wrapping `qpdfjob_run_from_json` along with three functions for `info`, `warn`, and `error`. When executed from C# (.NET Framework 4.8), the outcome is:

```
My own wrap for RunFromJSON returns the text of the C++ exception: error logger function returned code 13000
Info: checking
Warn:
Error: qpdfjob json
```

The returned code varies between runs, displaying values such as -1192807736 or 289878728 or something else. The error with the logger function seems to be related to the `StringBuilder` and `Marshalling` in .NET Framework 4.8, at least based on my speculation. Do you have any ideas what I could do?

Unfortunately, turning "Prefer 32-bit" on or off didn't help.

**Comment by Sicos1977** [comment]
I have to look into that this weekend, interop is always tricky stuff to debug. Marshalling between managed and unmanaged languages can sometimes give very weird errors.... and I'm not "the expert" in that part of programming.

There is also a new qpdf version that I still want to use in the package so I'm probably going to update to that version first.... maybe we are lucky and that solves the problem.... keeping my fingers crossed.

**Comment by Sicos1977** [comment]
If you want to test this yourself than just get the files from here and copy them to the x86 and x64 folders in your project. Make sure that they don't get overwritten when rebuilding your app.

**Comment by deralbert** [comment]
> I have to look into that this weekend, interop is always tricky stuff to debug. Marshalling between managed and unmanaged languages can sometimes give very weird errors.... and I'm not "the expert" in that part of programming.
> 
> There is also a new qpdf version that I still want to use in the package so I'm probably going to update to that version first.... maybe we are lucky and that solves the problem.... keeping my fingers crossed.

I already tried the newest version of qpdf29.dll, it unfortunately didn't help.

**Comment by deralbert** [comment]
Please ignore the first commit, it should be deleted as well as the link to it in this discussion. The only relevant PR is here: https://github.com/Sicos1977/QPdfNet/pull/9/ .

**Comment by Sicos1977** [comment]
A new package is just published
